# ใช้ Node.js base image
FROM node:18

# ตั้ง working directory
WORKDIR /usr/src/app

# คัดลอกไฟล์ package.json และ package-lock.json
COPY package*.json ./

# ติดตั้ง dependencies
RUN npm install

# คัดลอกไฟล์ทั้งหมดใน backend
COPY . .

# เปิดพอร์ตที่ backend ใช้งาน (เช่น 5000)
EXPOSE 3001

# คำสั่งเริ่มต้นสำหรับรัน backend
CMD ["npm", "start"]